"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase/client";

const blankQuestion = { id: "", question: "", answer: "", mode: "exact", category: "", quiz: "Quiz 1" };
const existingQuestionIds = ["purpose","motto","alphabet","Flower","Gem","Colors","Uni","City","State","Date","OGName","Founders","DeadOrAlive", ...Array.from({ length: 24 }, (_, i) => `CoatOfArms${i + 1}`), ...Array.from({ length: 12 }, (_, i) => `ChapterExecutiveCouncil${i + 1}`), ...Array.from({ length: 9 }, (_, i) => `GrandExecutiveCouncil${i + 1}`), ...Array.from({ length: 5 }, (_, i) => `Flag${i + 1}`), "Regions1", "Regions2", ...Array.from({ length: 13 }, (_, i) => `Chapters${i + 1}`), ...Array.from({ length: 5 }, (_, i) => `Requirement${i + 1}`), "Other", ...Array.from({ length: 10 }, (_, i) => `MemberBadge${i + 1}`), ...Array.from({ length: 8 }, (_, i) => `CompetingFraternitiesSororities${i + 1}`), ...Array.from({ length: 3 }, (_, i) => `DeltaGammaSigDates${i + 1}`), ...Array.from({ length: 3 }, (_, i) => `ThetaTauSigDates${i + 1}`)];

export default function StaffPortal({ profile }) {
  const [members, setMembers] = useState([]); const [progress, setProgress] = useState([]); const [attempts, setAttempts] = useState([]); const [questions, setQuestions] = useState([]);
  const [question, setQuestion] = useState(blankQuestion); const [invite, setInvite] = useState({ email: "", name: "", role: "pnm" }); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const supabase = useMemo(() => createClient(), []); const isAdmin = profile.role === "admin";
  async function refresh() {
    setLoading(true);
    const [memberResult, progressResult, attemptResult, questionResult] = await Promise.all([
      supabase.from("profiles").select("id, email, display_name, role, created_at").order("created_at", { ascending: false }), supabase.from("question_progress").select("user_id, question_id, correct_count, wrong_count, mastered, updated_at"), supabase.from("quiz_attempts").select("user_id, quiz_name, score, total, completed_at").order("completed_at", { ascending: false }), supabase.from("study_questions").select("id, question, answer, mode, category, quiz, is_custom, updated_at").order("updated_at", { ascending: false })
    ]);
    if (memberResult.error || progressResult.error || attemptResult.error || questionResult.error) setNotice("A portal query failed. Confirm the latest Supabase migration has been run.");
    else { setMembers(memberResult.data || []); setProgress(progressResult.data || []); setAttempts(attemptResult.data || []); setQuestions(questionResult.data || []); }
    setLoading(false);
  }
  useEffect(() => { refresh(); }, []);
  const memberRows = members.map(member => { const items = progress.filter(item => item.user_id === member.id); const latest = attempts.find(item => item.user_id === member.id); return { ...member, attempted: items.length, mastered: items.filter(item => item.mastered).length, latest }; });
  const pnmRows = memberRows.filter(member => member.role === "pnm"); const totalMastered = pnmRows.reduce((sum, member) => sum + member.mastered, 0);
  async function saveQuestion(event) { event.preventDefault(); const id = question.id.trim() || `custom-${crypto.randomUUID()}`; const { error } = await supabase.from("study_questions").upsert({ id, question: question.question.trim(), answer: question.answer.trim(), mode: question.mode, category: question.category.trim() || null, quiz: question.quiz.trim() || "Quiz 1", is_custom: !questions.some(item => item.id === id) }); if (error) return setNotice(error.message); setNotice("Question saved. It will appear in the guide on the next refresh."); setQuestion(blankQuestion); refresh(); }
  async function removeQuestion(id) { if (!window.confirm("Remove this custom or overridden question?")) return; const { error } = await supabase.from("study_questions").delete().eq("id", id); setNotice(error ? error.message : "Question change removed."); if (!error) refresh(); }
  async function sendInvite(event) { event.preventDefault(); const response = await fetch("/api/admin/invite", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(invite) }); const result = await response.json(); setNotice(result.error || "Invitation sent. They can set their password from the email."); if (response.ok) { setInvite({ email: "", name: "", role: "pnm" }); refresh(); } }
  return <main className="staffPage"><header className="staffHeader"><a href="/study-guide/">← Study guide</a><div><span>{isAdmin ? "Administrator" : "NME"}</span><h1>Pledge-class staff portal</h1></div><button onClick={refresh} type="button">Refresh</button></header>{notice && <p className="staffNotice">{notice}</p>}
    <section className="staffMetrics"><article><strong>{pnmRows.length}</strong><span>PNMs</span></article><article><strong>{progress.length}</strong><span>Cards attempted</span></article><article><strong>{totalMastered}</strong><span>Cards mastered</span></article><article><strong>{attempts.length}</strong><span>Quiz attempts</span></article></section>
    <section className="panel"><div className="panelHeading"><div><p>Live progress</p><h2>PNM readiness</h2></div>{loading && <span>Loading…</span>}</div><div className="tableWrap"><table><thead><tr><th>Member</th><th>Role</th><th>Attempted</th><th>Mastered</th><th>Latest quiz</th></tr></thead><tbody>{memberRows.map(member => <tr key={member.id}><td>{member.display_name || "—"}<small>{member.email}</small></td><td><b>{member.role}</b></td><td>{member.attempted}</td><td>{member.mastered}</td><td>{member.latest ? `${member.latest.score}/${member.latest.total} · ${member.latest.quiz_name}` : "—"}</td></tr>)}{!memberRows.length && <tr><td colSpan="5">No members yet.</td></tr>}</tbody></table></div></section>
    {isAdmin && <section className="panel"><div className="panelHeading"><div><p>Access</p><h2>Invite a member</h2></div></div><form className="formGrid" onSubmit={sendInvite}><input required type="email" placeholder="Email address" value={invite.email} onChange={e => setInvite({ ...invite, email: e.target.value })} /><input placeholder="Display name" value={invite.name} onChange={e => setInvite({ ...invite, name: e.target.value })} /><select value={invite.role} onChange={e => setInvite({ ...invite, role: e.target.value })}><option value="pnm">PNM</option><option value="nme">NME</option><option value="admin">Admin</option></select><button>Send invite</button></form><p className="hint">The invite email lets them choose their own password. Never share a password with them.</p></section>}
    {isAdmin ? <section className="panel"><div className="panelHeading"><div><p>Content</p><h2>Questions</h2></div></div><form className="questionForm" onSubmit={saveQuestion}><input list="questionIds" placeholder="Existing question ID to override, or leave empty to add a new one" value={question.id} onChange={e => setQuestion({ ...question, id: e.target.value })} /><datalist id="questionIds">{existingQuestionIds.map(id => <option key={id} value={id} />)}</datalist><input required placeholder="Question" value={question.question} onChange={e => setQuestion({ ...question, question: e.target.value })} /><textarea required placeholder="Answer" value={question.answer} onChange={e => setQuestion({ ...question, answer: e.target.value })} /><div className="formGrid"><select value={question.mode} onChange={e => setQuestion({ ...question, mode: e.target.value })}><option value="exact">Exact</option><option value="contains">Contains</option><option value="multi">Multiple accepted answers</option></select><input placeholder="Category" value={question.category} onChange={e => setQuestion({ ...question, category: e.target.value })} /><input placeholder="Quiz 1" value={question.quiz} onChange={e => setQuestion({ ...question, quiz: e.target.value })} /><button>Save question</button></div></form><div className="questionList">{questions.map(item => <article key={item.id}><div><b>{item.question}</b><small>{item.id} · {item.quiz || "Quiz 1"} · {item.is_custom ? "Custom" : "Override"}</small></div><button onClick={() => setQuestion({ id: item.id, question: item.question, answer: item.answer, mode: item.mode, category: item.category || "", quiz: item.quiz || "Quiz 1" })}>Edit</button><button className="danger" onClick={() => removeQuestion(item.id)}>Remove</button></article>)}{!questions.length && <p className="hint">No saved edits yet. Add a new question or use an existing question ID to override it.</p>}</div></section> : <section className="panel"><div className="panelHeading"><div><p>Content</p><h2>Question library</h2></div></div><p className="hint">Question editing is restricted to admins. You still have access to member progress and invite links.</p></section>}
    <style jsx>{`.staffPage{min-height:100vh;padding:32px clamp(18px,5vw,72px) 72px;background:#160303;color:#fff8ef;font-family:Arial,sans-serif}.staffHeader{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:28px}.staffHeader a{color:#e6c66d;text-decoration:none}.staffHeader h1{margin:6px 0 0;font-size:clamp(26px,4vw,42px)}.staffHeader span,.panelHeading p,.hint,small{color:#c7b5ad}.staffHeader button,.formGrid button,.questionForm button,.questionList button{border:0;border-radius:10px;padding:11px 14px;background:#d7b34f;color:#291505;font-weight:700;cursor:pointer}.staffMetrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:22px}.staffMetrics article,.panel{border:1px solid rgba(255,255,255,.12);border-radius:16px;background:#250b0b;padding:20px}.staffMetrics strong{display:block;font-size:32px;color:#efd079}.staffMetrics span{color:#c7b5ad}.panel{margin-top:20px}.panelHeading{display:flex;justify-content:space-between;align-items:start;margin-bottom:16px}.panelHeading p{margin:0;text-transform:uppercase;font-size:12px;letter-spacing:.12em}.panelHeading h2{margin:6px 0 0}.tableWrap{overflow:auto}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:13px;border-top:1px solid rgba(255,255,255,.1)}th{color:#d9c7bc;font-size:13px}td small{display:block;margin-top:4px}td b{text-transform:uppercase;font-size:12px;color:#edcb6f}.formGrid{display:grid;grid-template-columns:2fr 1.3fr 1fr auto;gap:10px}.questionForm{display:grid;gap:10px}.questionList{display:grid;gap:8px;margin-top:20px}.questionList article{display:flex;align-items:center;gap:8px;padding:12px;border-radius:10px;background:#1a0606}.questionList article div{flex:1}.questionList small{display:block;margin-top:5px}.questionList .danger{background:#7d2323;color:#fff}.staffNotice{padding:13px 16px;border-radius:10px;background:#432017;color:#f9d08c}.hint{font-size:13px}input,textarea,select{min-width:0;padding:12px;border:1px solid #704848;border-radius:9px;background:#150303;color:#fff8ef;font:inherit}textarea{min-height:90px;resize:vertical}@media(max-width:800px){.staffHeader{align-items:start;flex-wrap:wrap}.staffMetrics{grid-template-columns:repeat(2,1fr)}.formGrid{grid-template-columns:1fr}.questionList article{align-items:start;flex-wrap:wrap}}`}</style></main>;
}
