"use client";

import { useEffect, useState } from "react";

export default function InviteLinksPage() {
  const [links, setLinks] = useState([]); const [label, setLabel] = useState("Fall pledge class"); const [maxUses, setMaxUses] = useState(30); const [notice, setNotice] = useState("");
  async function load() { const response = await fetch("/api/invite-links"); const result = await response.json(); setLinks(result.links || []); if (result.error) setNotice(result.error); }
  useEffect(() => { load(); }, []);
  async function create(event) { event.preventDefault(); const response = await fetch("/api/invite-links", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, maxUses }) }); const result = await response.json(); if (!response.ok) return setNotice(result.error); setNotice(`New link: ${result.url}`); await navigator.clipboard.writeText(result.url); load(); }
  async function toggle(link) { const response = await fetch(`/api/invite-links/${link.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !link.active }) }); const result = await response.json(); setNotice(result.error || `${link.label} is now ${link.active ? "disabled" : "enabled"}.`); load(); }
  return <main className="invitePage"><a href="/study-guide/">← Study guide</a><p>PNM ACCESS</p><h1>Invite links</h1><section><h2>Create a link</h2><form onSubmit={create}><input value={label} onChange={e=>setLabel(e.target.value)} aria-label="Link label" required/><input type="number" min="1" max="500" value={maxUses} onChange={e=>setMaxUses(e.target.value)} aria-label="Maximum uses" required/><button>Create and copy link</button></form><small>Each link creates PNM accounts only. It stops automatically when it reaches its maximum.</small></section>{notice && <div className="notice">{notice}</div>}<section><h2>Existing links</h2>{links.map(link=><article key={link.id}><div><strong>{link.label}</strong><small>{link.use_count}/{link.max_uses} uses · {link.active ? "Active" : "Disabled"}</small></div><button onClick={()=>toggle(link)}>{link.active ? "Disable" : "Enable"}</button></article>)}{!links.length&&<small>No invite links yet.</small>}</section><style jsx>{`.invitePage{min-height:100vh;padding:40px max(20px,8vw);background:#160303;color:#fff8ef;font-family:Arial,sans-serif}.invitePage>a{color:#edcb6f;text-decoration:none}.invitePage>p{margin:28px 0 4px;color:#edcb6f;letter-spacing:.12em;font-size:12px;font-weight:bold}.invitePage h1{font-size:42px;margin:0 0 24px}.invitePage section{max-width:800px;margin-top:18px;padding:22px;border:1px solid rgba(255,255,255,.12);border-radius:16px;background:#250b0b}.invitePage h2{margin-top:0}.invitePage form{display:grid;grid-template-columns:2fr 1fr auto;gap:10px}.invitePage input,.invitePage button{padding:12px;border-radius:9px;font:inherit}.invitePage input{border:1px solid #704848;background:#150303;color:#fff8ef}.invitePage button{border:0;background:#d7b34f;color:#291505;font-weight:bold;cursor:pointer}.invitePage article{display:flex;justify-content:space-between;align-items:center;padding:13px 0;border-top:1px solid rgba(255,255,255,.1)}.invitePage article small,.invitePage section>small{display:block;margin-top:5px;color:#c7b5ad}.notice{max-width:800px;margin-top:18px;padding:14px;border-radius:10px;background:#432017;color:#f9d08c;word-break:break-all}@media(max-width:650px){.invitePage form{grid-template-columns:1fr}.invitePage h1{font-size:34px}}`}</style></main>;
}
